name: Comment on new PR

permissions:
  pull-requests: write

on:
  pull_request:
    branches: [master]
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #7.0.1
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you for opening the PR!\n\nThis comment will be replaced with a link to a Preview deployment as soon as it is ready.'
            })